name: Update docs
on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  update-docs:
    name: Update docs
    uses: unifyai/workflows/.github/workflows/docs.yml@master
    secrets: inherit
